import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CompanyStatus } from 'src/shared/enums/company.enums';

export type CompanyDocument = HydratedDocument<Company>;

@Schema({ collection: 'company_master' })
export class Company {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  companyId!: string;

  /* ======================================================
   * BASIC DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String, index: true })
  name!: string;

  @Prop({ trim: true, type: String, default: null })
  description?: string;

  /* ======================================================
   * CONTACT DETAILS
   * ====================================================== */

  @Prop({
    trim: true,
    lowercase: true,
    type: String,
    index: true,
    default: null,
  })
  email?: string;

  @Prop({
    required: true,
    trim: true,
    type: String,
    index: true,
  })
  mobile!: string;

  @Prop({
    trim: true,
    uppercase: true,
    type: String,
    index: true,
    default: null,
  })
  gstNumber?: string;

  /* ======================================================
   * ADDRESS
   * ====================================================== */

  @Prop({
    type: {
      line1: {
        type: String,
        required: true,
        trim: true,
        minlength: 3,
        maxlength: 150,
      },
      line2: { type: String, trim: true, maxlength: 150 },
      city: { type: String, trim: true },
      state: { type: String, trim: true },
      country: { type: String, trim: true, default: 'India' },
      pincode: { type: String, trim: true },
    },
    required: true,
  })
  address!: {
    line1: string;
    line2?: string;
    city?: string;
    state?: string;
    country?: string;
    pincode?: string;
  };

  /* ======================================================
   * BUSINESS DETAILS
   * ====================================================== */

  @Prop({
    type: [String],
    default: [],
  })
  services!: string[];

  @Prop({
    type: [String],
    default: [],
  })
  courses!: string[];

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: CompanyStatus,
    default: CompanyStatus.ACTIVE,
    index: true,
  })
  status!: CompanyStatus;
}

export const CompanySchema = SchemaFactory.createForClass(Company);
