import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { CustomerStatus } from 'src/shared/enums/customer.enums';

export type CustomerDocument = HydratedDocument<Customer>;

@Schema({ collection: 'customer_master' })
export class Customer {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  customerId!: string;

  @Prop({ required: true, type: String, index: true })
  roleId!: string;

  /* ======================================================
   * BASIC DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  firstName!: string;

  @Prop({ required: true, trim: true, type: String })
  lastName!: string;

  @Prop({
    trim: true,
    lowercase: true,
    type: String,
    index: true,
  })
  email?: string;

  @Prop({
    required: true,
    trim: true,
    index: true,
    type: String,
  })
  mobile!: string;

  @Prop({
    trim: true,
    uppercase: true,
    type: String,
    index: true,
  })
  gstNumber?: string;

  @Prop({ trim: true, type: String })
  companyName?: string;

  /* ======================================================
   * ADDRESS
   * ====================================================== */

  @Prop({
    type: {
      line1: {
        type: String,
        required: true,
        trim: true,
        minlength: 3,
        maxlength: 150,
      },
      line2: { type: String, trim: true, maxlength: 150 },
    },
    required: true,
  })
  address!: {
    line1: string;
    line2?: string;
  };

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: CustomerStatus,
    default: CustomerStatus.ACTIVE,
    index: true,
  })
  status!: CustomerStatus;
}

export const CustomerSchema = SchemaFactory.createForClass(Customer);
