import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { EmployeeStatus } from 'src/shared/enums/employee.enums';

export type EmployeeDocument = HydratedDocument<Employee>;

/* ======================================================
 * EMBEDDED SCHEMA: PermissionOverrides
 * ====================================================== */
@Schema({ _id: false }) // ✅ no separate _id
export class PermissionOverrides {
  @Prop({ type: [String], default: [] })
  allow!: string[];

  @Prop({ type: [String], default: [] })
  deny!: string[];
}

export const PermissionOverridesSchema = SchemaFactory.createForClass(PermissionOverrides);

/* ======================================================
 * MAIN SCHEMA: Employee
 * ====================================================== */
@Schema()
export class Employee {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({
    required: true,
    trim: true,
    unique: true,
    index: true,
    type: String,
  })
  employeeId!: string;

  @Prop({
    required: true,
    trim: true,
    unique: true,
    sparse: true,
    index: true,
    type: String,
  })
  mobile!: string;

  @Prop({
    required: true,
    trim: true,
    index: true,
    type: String,
  })
  name!: string;

  @Prop({
    required: false,
    lowercase: true,
    trim: true,
    unique: true,
    sparse: true,
    index: true,
    type: String,
  })
  email?: string;

  /* ======================================================
   * AUTHORIZATION
   * ====================================================== */

  @Prop({
    required: true,
    type: String,
    index: true,
  })
  roleId!: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: EmployeeStatus,
    default: EmployeeStatus.ACTIVE,
    index: true,
  })
  status!: EmployeeStatus;

  /* ======================================================
   * PERMISSION OVERRIDES
   * ====================================================== */

  @Prop({
    type: PermissionOverridesSchema, // ✅ FIXED
    default: { allow: [], deny: [] },
  })
  permissionOverrides!: PermissionOverrides;
}

export const EmployeeSchema = SchemaFactory.createForClass(Employee);

/* ======================================================
 * INDEXES (OPTIONAL)
 * ====================================================== */

// EmployeeSchema.index({ roleId: 1, status: 1 });
