import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { InquiryStatus } from 'src/shared/enums/inquiry.enums';

export type InquiryDocument = HydratedDocument<Inquiry>;

@Schema()
export class Inquiry {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  inquiryId!: string;

  /* ======================================================
   * PRODUCT DETAILS (SNAPSHOT)
   * ====================================================== */

  @Prop({
    required: true,
    type: String,
    ref: 'product_master',
    index: true,
  })
  productId!: string;

  // Store product name snapshot (important for history)
  @Prop({ required: true, trim: true, type: String })
  productName!: string;

  /* ======================================================
   * CUSTOMER
   * ====================================================== */

  @Prop({
    required: true,
    type: String,
    ref: 'customer_master',
    index: true,
  })
  customerId!: string;

  @Prop({
    required: true,
    type: String,
    index: true,
  })
  customerName!: string;

  /* ======================================================
   * PRICING
   * ====================================================== */

  @Prop({ required: true, type: Number })
  basePrice!: number;

  @Prop({ required: true, type: Number })
  customerPrice!: number;

  @Prop({ type: Number, default: 0 })
  offeredPrice!: number;

  /* ======================================================
   * QUANTITY
   * ====================================================== */

  @Prop({ required: true, type: Number })
  customerQuantity!: number;

  @Prop({ default: 0, type: Number })
  offeredQuantity!: number;

  @Prop({ type: Number, required: true })
  estimatedValue!: number;

  @Prop({ type: String })
  remark!: string;

  @Prop({ type: String })
  comments!: string;

  @Prop({ type: String, required: true })
  purpose!: string;

  @Prop({ type: Date, required: true })
  deliveryRequiredBy!: Date;

  @Prop({ type: String, required: true })
  deliveryCity!: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: InquiryStatus,
    default: InquiryStatus.PENDING,
    index: true,
  })
  status!: InquiryStatus;
}

export const InquirySchema = SchemaFactory.createForClass(Inquiry);
