import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { PriceStatus, PriceType } from 'src/shared/enums/price.enums';

export type PriceDocument = HydratedDocument<Price>;

@Schema({ collection: 'price_master' })
export class Price {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  priceId!: string;

  /* ======================================================
   * ASSOCIATION
   * ====================================================== */

  @Prop({
    required: true,
    type: String,
    ref: 'product_master',
    index: true,
  })
  productId!: string;

  /* ======================================================
   * PRICE DETAILS
   * ====================================================== */

  @Prop({ required: true, type: Number })
  price!: number;

  @Prop({
    type: String,
    enum: PriceType,
    default: PriceType.STANDARD,
    index: true,
  })
  type!: PriceType;

  /* ======================================================
   * EFFECTIVE DATE
   * ====================================================== */

  @Prop({
    required: true,
    type: Date,
    index: true,
  })
  effectiveAt?: Date;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: PriceStatus,
    default: PriceStatus.ACTIVE,
    index: true,
  })
  status!: PriceStatus;
}

export const PriceSchema = SchemaFactory.createForClass(Price);
