import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { ProductStatus } from 'src/shared/enums/product.enums';

export type ProductDocument = HydratedDocument<Product>;

@Schema({ collection: 'product_master' })
export class Product {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  productId!: string;

  /* ======================================================
   * BASIC DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true, type: String })
  name!: string;

  @Prop({ trim: true, type: String })
  description?: string;

  /* ======================================================
   * ASSOCIATIONS
   * ====================================================== */

  @Prop({
    required: true,
    type: String,
    ref: 'product_category',
    index: true,
  })
  categoryId!: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: ProductStatus,
    default: ProductStatus.ACTIVE,
    index: true,
  })
  status!: ProductStatus;
}

export const ProductSchema = SchemaFactory.createForClass(Product);
