/**
 * Product Categories Collection
 * -----------------------------
 * Purpose : Product classification and grouping
 * Used by : BACK_OFFICE / ADMIN
 *
 * Contains:
 * - Category identity
 * - Category name
 * - Category status
 *
 * Notes:
 * - Categories are referenced by Product master
 * - Soft deletes preserve audit history
 */

import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import {
  ProductCategoryStatus,
  ProductCategoryTypes,
} from 'src/shared/enums/product-category.enums';

export type ProductCategoryDocument = HydratedDocument<ProductCategory>;

@Schema({
  collection: 'product_categories',
})
export class ProductCategory {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  // Unique business identifier for category
  @Prop({ required: true, unique: true, type: String })
  categoryId!: string;

  @Prop({ type: String })
  parentId!: string;

  @Prop({
    required: true,
    enum: ProductCategoryTypes,
    type: String,
  })
  type!: string;

  // Display name of category
  @Prop({ required: true, type: String })
  name!: string;

  /* ======================================================
   * STATUS
   * ====================================================== */

  // Category availability status
  @Prop({
    type: String,
    enum: ProductCategoryStatus,
    default: ProductCategoryStatus.ACTIVE,
  })
  status!: ProductCategoryStatus;
}

export const ProductCategorySchema = SchemaFactory.createForClass(ProductCategory);
