import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { Platform } from 'src/shared/enums/app.enums';
import { VersionStatus } from 'src/shared/enums/version.enums';

export type VersionDocument = HydratedDocument<Version>;

@Schema()
export class Version {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true })
  versionId!: string;

  /* ======================================================
   * VERSION DETAILS
   * ====================================================== */

  @Prop({
    required: true,
    trim: true,
    index: true,
    match: /^\d+\.\d+\.\d+$/, // ✅ semantic version validation
  })
  versionNumber!: string;

  @Prop({
    required: true,
    enum: Platform,
    type: String,
    index: true,
  })
  platform!: Platform;

  /* ======================================================
   * RELEASE NOTES
   * ====================================================== */

  @Prop({ type: String, default: '' })
  features?: string;

  @Prop({ type: String, default: '' })
  bugFixes?: string;

  /* ======================================================
   * UPDATE CONTROL
   * ====================================================== */

  @Prop({ type: Boolean, default: false })
  forceUpdate!: boolean;

  @Prop({ type: String, trim: true })
  minSupportedVersion?: string;

  /* ======================================================
   * LATEST FLAG (NEW)
   * ====================================================== */

  @Prop({ type: Boolean, default: false, index: true })
  isLatest!: boolean;

  /* ======================================================
   * OPTIONAL METADATA
   * ====================================================== */

  @Prop({ type: String })
  buildNumber?: string;

  @Prop({ type: String })
  downloadUrl?: string;

  @Prop({ type: Date })
  releaseDate?: Date;

  /* ======================================================
   * STATUS
   * ====================================================== */

  @Prop({
    type: String,
    enum: VersionStatus,
    default: VersionStatus.ACTIVE,
    index: true,
  })
  status!: VersionStatus;
}

export const VersionSchema = SchemaFactory.createForClass(Version);

/* ======================================================
 * INDEXES (IMPORTANT)
 * ====================================================== */

// Ensure only ONE latest version per platform
VersionSchema.index(
  { platform: 1, isLatest: 1 },
  { unique: true, partialFilterExpression: { isLatest: true } },
);

// Fast lookup for latest active version
VersionSchema.index({ platform: 1, status: 1, isLatest: 1 });

// Version sorting
VersionSchema.index({ platform: 1, versionNumber: -1 });
