import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';
import { AutoGenerated } from 'src/core/decorators/auto-generated.decorator';
import { Platform } from 'src/shared/enums/app.enums';
import { VersionStatus } from 'src/shared/enums/version.enums';

export type VersionDocument = HydratedDocument<Version>;

@Schema()
export class Version {
  /* ======================================================
   * IDENTITY
   * ====================================================== */

  @AutoGenerated()
  @Prop({ required: true, unique: true, index: true, type: String })
  versionId!: string;

  /* ======================================================
   * VERSION DETAILS
   * ====================================================== */

  @Prop({ required: true, trim: true })
  versionNumber!: string; // e.g. "1.2.0"

  @Prop({
    required: true,
    enum: Platform,
    type: String,
    index: true,
  })
  platform!: Platform;

  /* ======================================================
   * RELEASE NOTES
   * ====================================================== */

  @Prop({ type: String, default: '' })
  whatsNew?: string;

  /* ======================================================
   * UPDATE CONTROL
   * ====================================================== */

  @Prop({ type: Boolean, default: false })
  forceUpdate!: boolean;

  /* ======================================================
   * OPTIONAL (RECOMMENDED)
   * ====================================================== */

  @Prop({ type: String })
  minSupportedVersion?: string;

  @Prop({
    type: String,
    enum: VersionStatus,
    default: VersionStatus.ACTIVE,
    index: true,
  })
  status!: VersionStatus;
}

export const VersionSchema = SchemaFactory.createForClass(Version);
